// <auto-generated />
namespace PhotoGallery.Data.Migrations.UserMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201510242254027_initialUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
