// <auto-generated />
namespace PhotoGallery.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initilisegallery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initilisegallery));
        
        string IMigrationMetadata.Id
        {
            get { return "201510222133246_initilise-gallery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
